Test enumerable module
AndresFMoya/enumerable_methods pull request #3
Opened 2019-09-20 20:46 UTC by AndresFMoya

2019-09-21 08:26 UTC, Oghenebrume50 requested changes
Hi, Team, this is a really good written test :clap: the only thing left to do now is to use make sure negative and positive scenarios are covered, this is done for cases like my_each and my_each_with_index but the other's aren't covered.

Basically positive and negative means that, if you test for the truthy outcome of a method you want to also make a test for the falsy outcome.

2019-09-21 14:45 UTC, AndresFMoya commented
Hi @Oghenebrume50. Thanks for your feedback. We add negative test cases to the remaining methods. Now we have 12 test cases. 2 for every method. We sent a new code review request. Regards!

2019-09-22 17:42 UTC, bolah2009 requested changes
# Awesome job @AndresFMoya 

### Almost there :smile: 

Let's cover more cases in the test for the following methods:
- `my_any?`
- `my_none?`

- Let's make this PR (Pull Request) look more professional. [See below]()
  - [REQUIRED] Use meaningful names for  Pull Requests.
  - [REQUIRED] Add a short summary of changes in Pull Request description.

#### :recycle:  Make these changes and submit another code review request. :+1: 

#### Feel free to reach me on slack if you having issues implementing these features. :+1: 

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

2019-09-22 17:42 UTC, bolah2009 commented on spec/enumerable_spec.rb
> +  arr = (1..10).to_a
Consider using `let` helper here instead.
> Use let to define a memoized helper method. The value will be cached
across multiple calls in the same example but not across examples.

```suggestion
  let(:arr){(1..10).to_a}
```

#### Learn more about [`let` here](https://relishapp.com/rspec/rspec-core/v/2-5/docs/helper-methods/let-and-let).

2019-09-22 17:42 UTC, bolah2009 commented on spec/enumerable_spec.rb
> +  context 'When the block returns true to every element' do
What happens when no block is given?

```ruby
  def my_any?(arg = nil)
    if block_given?
      my_each { |item| return true if yield(item) }
    # elsif arg.nil?
    #   my_each { |item| return true if item }
    # else
    #   my_each { |item| return true if item.class == arg }
    end
    false
  end
```

Currently, the above method passes the test. Please, let's test for the commented out cases.
- when an argument is not passed and no block is given.
- when an argument is passed and no block is given.

2019-09-22 17:42 UTC, bolah2009 commented on spec/enumerable_spec.rb
> +    describe '#my_none?' do
What happens when no block is given? :thinking: 

```ruby
  def my_none?(&block)
    result = true
    if block
      my_each { |e| result = false if yield(e) }
    # else
    #   my_each { |e| result = false if e }
    end
    result
  end
```

Currently, the above method passes the test. Please, let's test for the commented out cases.
- when no block is given.

2019-09-23 15:33 UTC, rOluochKe commented on spec/enumerable_spec.rb
> +  arr = (1..10).to_a
resolved

2019-09-23 16:08 UTC, rOluochKe commented on spec/enumerable_spec.rb
> +    describe '#my_none?' do
added when no block is given

2019-09-23 16:19 UTC, rOluochKe commented on spec/enumerable_spec.rb
> +  context 'When the block returns true to every element' do
done - when an argument is not passed and no block is given
done - when an argument is passed and no block is given.

2019-09-24 00:58 UTC, Torres-ssf commented
### Pull Request Under Review By Sérgio (TSE)

2019-09-24 01:19 UTC, Torres-ssf approved these changes
### Hi there team :hand: 

Great job implementing the required changes :clap: 
### I'm approving this project :+1: 

Good luck with the next project. Happy coding :computer:

2019-09-24 01:48 UTC, merged